name: Build and Deploy Tic Tac Toe

on:
  push:
    branches:
      - main  # Adjust as per your main branch name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.0'  # Adjust to your Qt version
        host: 'linux'
        target: 'desktop'
        dir: ${{ runner.workspace }}/Qt

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev

    - name: Build project
      run: |
        mkdir -p build
        cd build
        /path/to/Qt/6.7.0/gcc_64/bin/qmake ../  # Adjust path to qmake
        make VERBOSE=1

    - name: Run tests (optional)
      run: |
        # Add your test commands here
        # Example: ctest --output-on-failure

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tic-tac-toe-build
        path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: tic-tac-toe-build

    # Add deployment steps as per your specific deployment needs (e.g., SCP, SSH)

